env:
  es2021: true
  browser: true

extends:
  - airbnb
  - plugin:react/recommended
  - plugin:react-hooks/recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  import/extensions: 0
  import/no-unresolved: 0
  no-console: 0
  react/react-in-jsx-scope: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  react/jsx-uses-react: 0
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  react/prop-types: 0
  react/jsx-props-no-spreading: 0

globals:
  localStorage: true
